#!/bin/bash
# Regenerate lib/casefold_data.ml from Unicode's CaseFolding.txt.
# Uses statuses C and F: the full case folding of Python's str.casefold.
#   scripts/gen-casefold.sh [UNICODE_VERSION]
set -euo pipefail
VERSION="${1:-16.0.0}"
cd "$(dirname "$0")/.."
{
    echo "(* Generated by scripts/gen-casefold.sh from Unicode $VERSION CaseFolding.txt"
    echo "   (statuses C and F, as Python's str.casefold). Do not edit. *)"
    echo
    echo "let unicode_version = \"$VERSION\""
    echo
    curl -fsSL "https://www.unicode.org/Public/$VERSION/ucd/CaseFolding.txt" |
        awk -F'; ' '$2 == "C" || $2 == "F" {
            keys = keys sprintf("0x%s; ", $1)
            starts = starts sprintf("%d; ", count)
            n = split($3, to, " ")
            for (i = 1; i <= n; i++) { folds = folds sprintf("0x%s; ", to[i]); count++ }
        }
        END {
            # Flat int arrays keep the table unboxed: code point keys[i] folds
            # to folds.(starts.(i)) up to folds.(starts.(i + 1)) exclusive.
            print "(* Sorted code points with a folding. *)"
            printf "let keys = [|%s|]\n\n", keys
            print "(* Where each key'"'"'s folding starts in [folds], plus the end. *)"
            printf "let starts = [|%s%d|]\n\n", starts, count
            print "let folds = [|" folds "|]"
        }' | fold -w 100 -s | sed 's/ *$//'
} > lib/casefold_data.ml
echo "Wrote lib/casefold_data.ml from Unicode $VERSION"
